version: '3.6'
name: "backend"
services:
  postgres_dev:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "shop_admin"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}