version: '3.6'
name: "backend"
services:
  postgres_dev:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "shop_admin"
      POSTGRES_PASSWORD: "dbadmin"
    volumes:
      - ./script/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql:ro