version: '3.6'
services:
  postgres_test:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "shop_admin"
      POSTGRES_PASSWORD: "test"