spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/shop"
    username: "shop_admin"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true