spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/shop"
    username: "shop_admin"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


security:
  token:
    timeout_in_minutes: 10
    key: "r7sHH+ErDOdwvIWmE6OxD/PRXcJmicWSRnX1seiFV61wuV62CSR/L/HYPlED8GlC6e559dQv7a/jUmD6oC/FbwhmHeqqX9IvFv0WsWygpKA="
