spring:
  application:
    name: Shop
  profiles:
    active: dev
server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:https_private_key.p12
    key-store-password:

