db:
  datasource:
    init-module:
      persistence-unit-name: initPU
      url: jdbc:postgresql://localhost:5432/shop
      username: shop_admin
      password: dbadmin
      jpa:
        database-action: drop_and_create
      sql:
        enable: true
        data-locations:
          - script/data.sql
          - script/permissions.sql

    accounts-module:
      persistence-unit-name: accountsPU
      url: jdbc:postgresql://localhost:5432/shop
      username: shop_accounts
      password: dbaccounts

app:
  auth:
    unsuccessful_attempts: 3
    blockade_time_in_minutes: 5

security:
  token:
    timeout_in_minutes: 10
    key: "r7sHH+ErDOdwvIWmE6OxD/PRXcJmicWSRnX1seiFV61wuV62CSR/L/HYPlED8GlC6e559dQv7a/jUmD6oC/FbwhmHeqqX9IvFv0WsWygpKA="
  refresh_token:
    timeout_in_minutes: 1140
    key: "lPe/UW3XpvXCA8QZihq1Izy0Xhiz9YG7ZQkjFxgBIoWOooX8YBdHqvVFhL5CLhK/bm++L27Hyc7fzemv6vA1KQ0dFgd58c756ehFQBfg8SE="
