spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/shop"
    username: "shop_admin"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


app:
  auth:
    unsuccessful_attempts: 3
    blockade_time_in_minutes: 5

security:
  token:
    timeout_in_minutes: 5
    key: "r7sHH+ErDOdwvIWmE6OxD/PRXcJmicWSRnX1seiFV61wuV62CSR/L/HYPlED8GlC6e559dQv7a/jUmD6oC/FbwhmHeqqX9IvFv0WsWygpKA="
  refresh_token:
    timeout_in_minutes: 1140
    key: "lPe/UW3XpvXCA8QZihq1Izy0Xhiz9YG7ZQkjFxgBIoWOooX8YBdHqvVFhL5CLhK/bm++L27Hyc7fzemv6vA1KQ0dFgd58c756ehFQBfg8SE="
